### ISSUE TITLE
be able to select the photos to display

### ISSUE THREAD

**Issue by Fa10175** [JustCarmen/webtrees-fancy-imagebar#41]
On 1.7, it is possible to select photos to be display for a tree.
no in 2.07 may be an evolution for the futur.

**Comment by JustCarmen** [comment]
Maybe. I have removed it because of performance reasons. There were problems reported on large tree sites with lots of media. And in fact it is a lot of extra code and since the whole module had to be rewritten for webtrees 2 I've made the choice to simplify things. 
You still have control over which media you want to show. You could place those images in a separate folder or give them the same image type which you don't use for other images.

**Comment by kexuebin** [comment]
There are many trees,It is difficult to display different pictures according to different trees
