### ISSUE TITLE
Limit # of pictures

### ISSUE THREAD

**Issue by phildtmm** [JustCarmen/webtrees-fancy-imagebar#57]
Per another posting, I created a new directory in my media folder and copied a number of pictures from the main picture folder to the new directory.  The new directory appears in the drop down and I have selected that entry.  However, now the fancy bar no longer appears when I go back to my main page.

**Comment by JustCarmen** [comment]
There must be a link with a tree in order to show images in the Fancy Imagebar. 

So you should create media objects from the images in the new directory.
Go to Control Panel / Media / Manage Media. Select unused files and the newly added directory. You will get a list of all files not linked to a tree. Create the media object by clicking on the appropriate link. You might want to fill the form with a title and/or media type and click save. You will now be redirected to the media object page where you can link the image to an individual, family or source. The latter is not obligated to show the image in the Fancy Imagebar, but it is necessary if you want the image to contain a clickable link to that individual/family or source.

**Comment by phildtmm** [comment]
Thanks for the feedback - I was wondering how that link worked in
      the image bar so making the association/link is logical.
    
    Carmen wrote on 11/29/20 3:06 AM:
    
    
      
      There must be a link with a tree in order to show images in the
        Fancy Imagebar.
      So you should create media objects from the images in the new
        directory.
        Go to Control Panel / Media / Manage Media. Select unused files
        and the newly added directory. You will get a list of all files
        not linked to a tree. Create the media object by clicking on the
        appropriate link. You might want to fill the form with a title
        and/or media type and click save. You will now be redirected to
        the media object page where you can link the image to an
        individual, family or source. The latter is not obligated to
        show the image in the Fancy Imagebar, but it is necessary if you
        want the image to contain a clickable link to that
        individual/family or source.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/57#issuecomment-735358563",
"url": "https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/57#issuecomment-735358563",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
